# Windows Console Settings
# Author    : Elderry
# References: https://docs.microsoft.com/en-us/previous-versions/windows/it-pro/windows-2000-server/cc978570(v=technet.10),
#             https://docs.microsoft.com/en-us/windows-server/get-started/whats-new-in-console
#             https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-shllink/e6b432b4-5a49-4826-9c25-e28695e8dd0c
#             https://devblogs.microsoft.com/commandline/understanding-windows-console-host-settings/

# Defines the colors in the color well on the Colors tab of the console Properties or Defaults dialog box.
# Each of the 16 ColorTable x entries corresponds to one of the registry entries ColorTable00-ColorTable15.
# References: https://devblogs.microsoft.com/commandline/updating-the-windows-console-colors/ (default)
#             https://github.com/microsoft/terminal/blob/main/src/cascadia/TerminalSettingsModel/defaults.json#L166 (One Half Light)
#             Committed on Dec 16, 2020
Black        : '383A42'
DarkBlue     : '0184BC'
DarkGreen    : '50A14F'
DarkCyan     : '0997B3'
DarkRed      : 'E45649'
DarkMagenta  : 'A626A4'
DarkYellow   : 'C18301'
DarkWhite    : 'FAFAFA'
BrightBlack  : '4F525D'
BrightBlue   : '61AFEF'
BrightGreen  : '98C379'
BrightCyan   : '56B5C1'
BrightRed    : 'DF6C75'
BrightMagenta: 'C577DD'
BrightYellow : 'E4C07A'
White        : 'FFFFFF'

# 'false' enables new key shortcuts; 'true' disables them.
CtrlKeyShortcutsDisabled: false

# The code page console uses, avaliable values are listed in following link:
# https://docs.microsoft.com/en-us/windows/desktop/Intl/code-page-identifiers
CodePage: 65001

# Specifies the percentage of a character cell that the cursor occupies, avaliable values are:
# 'small'(25%), 'medium'(50%) and 'large'(100%).
CursorSize: large

# 'True' enables the full set of keyboard selection keys; 'false' disables them.
ExtendedEditKey: true

# 'True' enables new paste behavior.
FilterOnPaste: true

# Specifies the name of an alternate command window font. If there is no font name in the value of this entry,
# the system uses raster fonts.
FaceName: Sarasa Mono SC

# 'True' enables all new console features; 'false' disables all new features.
ForceV2: true

# Specifies the family of the font used in the console window. The values for the font family are:
# 'dontCare'  : The font family is unknown.
# 'roman'     : The font is variable-width with serifs; for example, "Times New Roman".
# 'swiss'     : The font is variable-width without serifs; for example, "Arial".
# 'modern'    : The font is fixed-width, with or without serifs; for example, "Courier New".
# 'script'    : The font is designed to look like handwriting; for example, "Cursive".
# 'decorative': The font is a novelty font; for example, "Old English".
FontFamily.Family: modern
# Specifies the font is a fixed-pitch font or does not apply any.
FontFamily.Pitch: false
# Specifies the font is a vector font.
FontFamily.Vector: true
# Specifies the font is a true-type font.
FontFamily.TrueType: true
# Specifies the font is specific to the device.
FontFamily.Device: false

# Specifies the size of the font used in the command window.
FontSize: 22

# Specifies the number of commands that can be stored in each command history buffer.
HistoryBufferSize: 999

# Specifies whether to remove duplicates in the history buffer.
HistoryNoDup: true

# Specifies how the system responds when the user types over existing characters.
InsertMode: true

# 'True' enables line selection; 'false' to use block mode only.
LineSelection: true

# 'True' wraps text when you resize console windows.
LineWrap: true

# Specifies the number of history buffers allocated to store commands.
NumberOfHistoryBuffers: 999

# Determines the size of the screen buffer (the screen that is retained in memory).
# If the size of the screen displayed on the monitor is smaller than the screen buffer, you can scroll to see the
# entire screen. You cannot display a console screen that is larger than the screen buffer.
ScreenBufferSize.Lines: 9999
# This option is disabled if 'LineWrap' is set to true.
ScreenBufferSize.Columns: 100

# Specifies the colors of console windows, possible values are the index of color in the color table above(0-15).
ScreenColors.Background: 15
ScreenColors.Foreground: 0

# Specifies whether QuickEdit mode is enabled. In QuickEdit mode, users can cut and paste text by using the mouse.
QuickEdit: true

# Sets opacity value between 30% and 100%.
WindowAlpha: 100

# Specifies the position of the command window on the user's screen.
WindowPosition.LeftMargin: 240
WindowPosition.TopMargin: 60

# Specifies the size of the command window.
WindowSize.Height: 30
WindowSize.Width: 120
